#!/usr/bin/env node

var osmtogeojson = require('./'),
    opt = require('optimist')
        .usage('Usage: $0 [-f format] [-e] FILE')
        .string('f').describe('f', 'file format. if not given, will be detected by filename. supported values: osm, json')
        .boolean('e').describe('e', 'enhanced properties. if set, the resulting GeoJSON feature\'s properties will contain more structured information')
        .boolean('version').describe('version','display software version')
        .boolean('help').describe('help','print this help message'),
    argv = opt.argv,
    fs = require('fs'),
    concat = require('concat-stream'),
    xmldom = new (require('xmldom').DOMParser)(),
    osmxml2osmjson = require('./parse_osmxml.js'),
    pack = require('./package.json');

if (argv.help) {
    return opt.showHelp();
}
if (argv.version) {
    process.stdout.write(pack.version+'\n');
    return;
}

var filename = argv._[0] || '';

var enhanced_geojson = argv.e;
var format = argv.f;

if (format === 'xml') format = 'osm';
// detect file format from filename
if (!format) {
    if (filename.match(/\.osm$/i)) format = 'osm';
    if (filename.match(/\.xml$/i)) format = 'osm';
    if (filename.match(/\.json$/i)) format = 'json';
}
// fall back to autodetection if still no format
if (!format) format = 'auto';

(filename ? fs.createReadStream(filename) : process.stdin).pipe(concat(convert));

function convert(data) {
    if (!data) data = ''; else data = data.toString();
    if (format === 'auto') {
        if (data.match(/^\s*</)) // (osm) xml files begin with a "<"
            format = 'osm';
        else if (data.match(/^\s*{/)) // osm json files begin with a "{"
            format = 'json';
        else {
            format = 'unknown';
        }
    }
    if (format === 'xmldom')
        data = xmldom.parseFromString(data);
    else if (format === 'json')
        data = JSON.parse(data);
    else if (format === 'osm' || format === 'fastxml')
        data = osmxml2osmjson(data);
    else {
        process.stderr.write('This doesn\'t look like a recognized file format.\n');
        return opt.showHelp();
    }
    var geojson = osmtogeojson(data, {
        flatProperties: !enhanced_geojson
    });
    // this is much faster than a simple JSON.stringify of the whole geojson
    // object. also, this is less memory intensive and output starts right
    // after the conversion without any additional delay
    process.stdout.on('error', function() {});
    process.stdout.write('{\n"type": "FeatureCollection",\n"features": [\n');
    geojson.features.forEach(function(f,i) {
        process.stdout.write(JSON.stringify(f, null, 4));
        if (i != geojson.features.length-1)
            process.stdout.write(',\n');
    });
    process.stdout.write('\n]\n}\n');
}