#!/usr/bin/env node

var osmtogeojson = require('./'),
    opt = require('optimist')
        .usage('Usage: $0 FILE'),
    argv = opt.argv,
    fs = require('fs'),
    concat = require('concat-stream'),
    xmldom = new (require('xmldom').DOMParser)();

var filename = argv._[0] || '';

if (process.stdin.isTTY && !argv._[0]) return opt.showHelp();

(argv._.length ? fs.createReadStream(argv._[0]) : process.stdin).pipe(concat(convert));

function convert(data) {
    process.stdout.write(
        JSON.stringify(
            osmtogeojson.toGeojson(
                xmldom.parseFromString(data.toString()),
                {flatProperties: true}
            ), null, 4
        )
    );
}